version: '3'

services: 
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes: 
      - ./Mongodb/data:/data/db
    container_name: "db"
    restart: always
  
  httpserver:
    image: peterscience/devenv
    ports:
      - "80:80"
    container_name: "lost"
    volumes:
      - ./:/data
    command:
      python3 resslserver.py
    restart: always

  sslserver: 
    image: peterscience/devenv
    volumes:
      - ./:/data
    container_name: "ring"
    ports:
      - "443:443"
    command: sh -c "(cd /data/ && git pull)&& python3 /data/setup.py runserver"
    restart: always
