version: '3'

services: 
  db:
    container_name: "db"
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes: 
      - ./Mongodb/data:/data/db
    command: [--auth]
    restart: always
  httpserver:
    image: peterscience/devenv
    ports:
      - "80:80"
    container_name: "lost"
    volumes:
      - ./:/data
    command:
      python3 resslserver.py
    restart: always

  sslserver: 
    image: peterscience/devenv
    volumes:
      - ./:/data
    container_name: "ring"
    ports:
      - "443:443"
    command: sh -c "(cd /data/ && git pull)&& (pip install -r requirements.txt) && python3 setup.py runserver"
    restart: always
